//
//  DataSource.swift
//  gitSwole
//
//  Created by Nicholas Amaya on 11/21/17.
//  Copyright © 2017 gitSwoleLLC. All rights reserved.
//

import Foundation
import FirebaseDatabase

/**
 *  FirebaseDatabaseReference wrapper (singleton object)
 */
class DataSource {
    
    static let dataSource = DataSource()
    
    private var dbref: DatabaseReference?

    
    init() {
        dbref = nil
    }
    
    func configure() {
        dbref = Database.database().reference()
    }
    
    func createUser(_ fbUserID:String, _ username:String) {
        print("Creating user in database backend..")
        let userDBRef = dbref?.child("users").childByAutoId()
        
        // save unique childID generated by childByAutoId()
        LocalDataSource.dataSource.saveUser(fbUserID, userDBRef!.key)
        
        userDBRef?.setValue(["username": username])
    }

//
//    // goal weight, current weight, current meal plan
//    func addCurrentMealPlan(_ mealPlan:Int) {
//        if signedIn() {
//            uid.setValue(["mealPlan": mealPlan])
////            uid.up
//        } else {
//            print("Not signed in")
//        }
//    }
//
////    func addGoalWeight
//
//    func test() {
//        if signedIn() {
//            let _ = user?.getIDToken(completion: { (id, error) in
//                if error == nil {
//                    self.dbref.setValue(id)
//                } else {
//                    print("Error: Failed to fetch User ID")
//                }
//            })
//        } else {
//            print("Not logged in")
//        }
//    }
}


