//
//  DataSource.swift
//  gitSwole
//
//  Created by Nicholas Amaya on 11/21/17.
//  Copyright © 2017 gitSwoleLLC. All rights reserved.
//

import Foundation
import FirebaseDatabase
import FirebaseAuth

/**
 *  FirebaseDatabaseReference wrapper (singleton object)
 */
class DataSource {
    
    static let dataSource = DataSource()
    
    private var dbref: DatabaseReference?
    private var userDBRef: DatabaseReference?
    
    init() {
        dbref = nil
        userDBRef = nil
    }
    
    func configure() {
        dbref = Database.database().reference()
    }
    
    // saves userID to CoreData
    func createUser(_ fbUserID:String, _ username:String) {
        print("Creating user in database backend..")
        userDBRef = dbref?.child("users").childByAutoId()
        
        // save unique childID generated by childByAutoId()
        LocalDataSource.dataSource.saveUser(fbUserID, userDBRef!.key)
        // Meal(first: "Scrambled Whole Egg - 3 Large", second: "Oatmeal bowl w/ yogurt - 1 cup", third: "Whole milk - 16 oz.", calories: 809),
        // Meal(first:"Chicken Breast - 6oz.", second:"Steamed White Rice - 1 cup", third:"Broccoli - 1 cup", calories: 445),
        // Meal(first:"Steak - 8 oz.", second:"Sweet Potato - 10 oz.", third:"Asparagus - 1 cup", calories: 845)]),
        let userDataModel:[String:Any] =
            ["username": username,
             "currentMealPlan":
                ["breakfast":
                    ["first": "Scrambled Whole Egg - 3 Large",
                     "second": "Oatmeal bowl w/ yogurt - 1 cup",
                     "third": "Whole milk - 16 oz."],
                 "lunch":
                    ["first": "Chicken Breast - 6oz.",
                     "second": "Steamed White Rice - 1 cup",
                     "third": "Broccoli - 1 cup"],
                 "dinner":
                    ["first": "Steak - 8 oz.",
                     "second": "Sweet Potato - 10 oz.",
                     "third": "Asparagus - 1 cup"]],
             "currentWeight": 170,
             "goalWeight": 150]
        
        userDBRef?.setValue(userDataModel)
    }
    
    // retrieves the userID from CoreData (must be signed in)
    func signIn() {

        userDBRef = dbref?.child(Auth.auth().currentUser!.uid)
    }
    
    func setCurrentMealPlan(_ mealPlan:[String:[String:String]]) {
        userDBRef?.child("currentMealPlan").setValue(mealPlan)
    }
    
    func listenToCurrentMeal(_ firstMealLabel:UILabel, _ secondMealLabel:UILabel, _ thridMealLabel:UILabel) {
        userDBRef?.child("currentMealPlan").child("breakfast").observe(DataEventType.value, with: { (snapshot) in
            firstMealLabel.text = snapshot.childSnapshot(forPath: "first").value as? String
            secondMealLabel.text = snapshot.childSnapshot(forPath: "second").value as? String
            thridMealLabel.text = snapshot.childSnapshot(forPath: "third").value as? String
        })
    }
    
    func listenForMealPlan(_ mealPlan:MealPlan) {
        userDBRef?.child("currentMealPlan").observe(DataEventType.value, with: { (snapshot) in
            let breakfastFirst = snapshot.childSnapshot(forPath: "breakfast").childSnapshot(forPath: "first").value as? String
            let breakfastSecond = snapshot.childSnapshot(forPath: "breakfast").childSnapshot(forPath: "second").value as? String
            let breakfastThird = snapshot.childSnapshot(forPath: "breakfast").childSnapshot(forPath: "third").value as? String
            let lunchFirst = snapshot.childSnapshot(forPath: "lunch").childSnapshot(forPath: "first").value as? String
            let lunchSecond = snapshot.childSnapshot(forPath: "lunch").childSnapshot(forPath: "second").value as? String
            let lunchThird = snapshot.childSnapshot(forPath: "lunch").childSnapshot(forPath: "third").value as? String
            let dinnerFirst = snapshot.childSnapshot(forPath: "dinner").childSnapshot(forPath: "first").value as? String
            let dinnerSecond = snapshot.childSnapshot(forPath: "dinner").childSnapshot(forPath: "second").value as? String
            let dinnerThird = snapshot.childSnapshot(forPath: "dinner").childSnapshot(forPath: "third").value as? String
            
            mealPlan.Meals = [
                Meal(first: breakfastFirst!, second: breakfastSecond!, third: breakfastThird!, calories: 500),
                Meal(first: lunchFirst!, second: lunchSecond!, third: lunchThird!, calories: 500),
                Meal(first: dinnerFirst!, second: dinnerSecond!, third: dinnerThird!, calories: 500),
            ]
        })
    }

//
//    // goal weight, current weight, current meal plan
//    func addCurrentMealPlan(_ mealPlan:Int) {
//        if signedIn() {
//            uid.setValue(["mealPlan": mealPlan])
////            uid.up
//        } else {
//            print("Not signed in")
//        }
//    }
//
////    func addGoalWeight
//
//    func test() {
//        if signedIn() {
//            let _ = user?.getIDToken(completion: { (id, error) in
//                if error == nil {
//                    self.dbref.setValue(id)
//                } else {
//                    print("Error: Failed to fetch User ID")
//                }
//            })
//        } else {
//            print("Not logged in")
//        }
//    }
}


